package lapr.project.ui;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import lapr.project.controller.CriarExposicaoController;
import lapr.project.model.*;
import lapr.project.utils.Data;

/**
 *
 * @author G29
 */
public class JFrameRegistarExpoUI extends javax.swing.JFrame {

    private ModeloJListPotenciaisOrganizadores model = new ModeloJListPotenciaisOrganizadores();
    private ComboBoxModelUtilizadores modelSelectOrg;
    private CriarExposicaoController ctrl;
    private List<Utilizador> lstUtilizadores;
    private Organizador organizadorSelecionado;

    private Data dataInicio, dataFim, dataInicioSubCand, dataFimSubCand, dataFimDetecaoConflitos;

    /**
     * Creates new form JFrameRegistarExpoUI
     */
    public JFrameRegistarExpoUI(CentroExposicoes ce) {
        super("Criar Exposiçao");
        ctrl = new CriarExposicaoController(ce);
        ctrl.novaExposicao();
        lstUtilizadores = inicializarLista();

        setLocationRelativeTo(null);
        setVisible(true);

        modelSelectOrg = new ComboBoxModelUtilizadores(lstUtilizadores);
        initComponents();
        setVisible(true);
        setMinimumSize(new Dimension(600, 300));
        setPreferredSize(new Dimension(600, 300));
    }

    public List<Utilizador> inicializarLista() {
        return ctrl.getListaUtilizadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        organizadoresList1 = new javax.swing.JList();
        cancelBtn1 = new javax.swing.JButton();
        dataAberturaSubmissaoLbl1 = new javax.swing.JLabel();
        anoFimDetecaoConflitos = new javax.swing.JComboBox<>();
        tituloTxt1 = new javax.swing.JTextField();
        registExpoBtn1 = new javax.swing.JButton();
        anoFimCand = new javax.swing.JComboBox<>();
        ucNameLbl1 = new javax.swing.JLabel();
        inicioExpoLbl1 = new javax.swing.JLabel();
        mesFimDetecaoConflitos = new javax.swing.JComboBox<>();
        anoInicio = new javax.swing.JComboBox<>();
        mesFim = new javax.swing.JComboBox<>();
        diaFimDetecaoConflitos = new javax.swing.JComboBox<>();
        organizadoresLbl1 = new javax.swing.JLabel();
        tituloLbl1 = new javax.swing.JLabel();
        diaFim = new javax.swing.JComboBox<>();
        addOrganizadorBtn = new javax.swing.JButton();
        textoDescritivoLbl1 = new javax.swing.JLabel();
        anoInicioCand = new javax.swing.JComboBox<>();
        dataEncerramentoSubmissaoCandLbl1 = new javax.swing.JLabel();
        mesFimCand = new javax.swing.JComboBox<>();
        removeOrganizadorBtn1 = new javax.swing.JButton();
        datasLbl1 = new javax.swing.JLabel();
        mesInicio = new javax.swing.JComboBox<>();
        localTxt1 = new javax.swing.JTextField();
        dataLimiteDetecaoConflitosLbl1 = new javax.swing.JLabel();
        mesInicioCand = new javax.swing.JComboBox<>();
        diaInicio = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        textoDescritivoTxt1 = new javax.swing.JTextArea();
        localLbl1 = new javax.swing.JLabel();
        anoFim = new javax.swing.JComboBox<>();
        dataFimExpoLbl1 = new javax.swing.JLabel();
        diaFimCand = new javax.swing.JComboBox<>();
        diaInicioCand = new javax.swing.JComboBox<>();
        selectOrgLbl1 = new javax.swing.JLabel();
        orgSelectionComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        organizadoresList1.setModel(model);
        jScrollPane3.setViewportView(organizadoresList1);

        cancelBtn1.setText("Cancelar");
        cancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn1ActionPerformed(evt);
            }
        });

        dataAberturaSubmissaoLbl1.setText("Abertura de submissão de candidaturas:");

        anoFimDetecaoConflitos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016" }));
        anoFimDetecaoConflitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoFimDetecaoConflitosActionPerformed(evt);
            }
        });

        tituloTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTxt1ActionPerformed(evt);
            }
        });

        registExpoBtn1.setText("Registar Exposição");
        registExpoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registExpoBtn1ActionPerformed(evt);
            }
        });

        anoFimCand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016" }));
        anoFimCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoFimCandActionPerformed(evt);
            }
        });

        ucNameLbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ucNameLbl1.setText(" Registar nova exposição ");
        ucNameLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inicioExpoLbl1.setText("Início da exposição:");

        mesFimDetecaoConflitos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        mesFimDetecaoConflitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesFimDetecaoConflitosActionPerformed(evt);
            }
        });

        anoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016" }));
        anoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoInicioActionPerformed(evt);
            }
        });

        mesFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        mesFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesFimActionPerformed(evt);
            }
        });

        diaFimDetecaoConflitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaFimDetecaoConflitosActionPerformed(evt);
            }
        });

        organizadoresLbl1.setText("Organizadores: (mínimo 2)");

        tituloLbl1.setText("Título da exposição:");

        diaFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaFimActionPerformed(evt);
            }
        });

        addOrganizadorBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        addOrganizadorBtn.setText("Adicionar Organizador");
        addOrganizadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizadorBtnActionPerformed(evt);
            }
        });

        textoDescritivoLbl1.setText("Texto Descritivo:");

        anoInicioCand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016" }));
        anoInicioCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoInicioCandActionPerformed(evt);
            }
        });

        dataEncerramentoSubmissaoCandLbl1.setText("Encerramento de submissão de candidaturas:");

        mesFimCand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        mesFimCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesFimCandActionPerformed(evt);
            }
        });

        removeOrganizadorBtn1.setText("Remover Organizador");
        removeOrganizadorBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrganizadorBtn1ActionPerformed(evt);
            }
        });

        datasLbl1.setText("Datas:");

        mesInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        mesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesInicioActionPerformed(evt);
            }
        });

        localTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localTxt1ActionPerformed(evt);
            }
        });

        dataLimiteDetecaoConflitosLbl1.setText("Limite de deteção de conflitos:");

        mesInicioCand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        textoDescritivoTxt1.setColumns(20);
        textoDescritivoTxt1.setRows(5);
        jScrollPane4.setViewportView(textoDescritivoTxt1);

        localLbl1.setText("Local:");

        anoFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016" }));
        anoFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoFimActionPerformed(evt);
            }
        });

        dataFimExpoLbl1.setText("Fim da exposição:");

        diaFimCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaFimCandActionPerformed(evt);
            }
        });

        diaInicioCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaInicioCandActionPerformed(evt);
            }
        });

        selectOrgLbl1.setText("Selecionar Organizador:");

        orgSelectionComboBox.setModel(modelSelectOrg);
        orgSelectionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgSelectionComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(card1Layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(organizadoresLbl1)
                        .addGap(41, 41, 41))
                    .addGroup(card1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(cancelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(card1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeOrganizadorBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(card1Layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)))))
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(selectOrgLbl1)
                        .addComponent(orgSelectionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                        .addComponent(addOrganizadorBtn)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                        .addComponent(registExpoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(mesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(card1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(card1Layout.createSequentialGroup()
                            .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(card1Layout.createSequentialGroup()
                                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(card1Layout.createSequentialGroup()
                                            .addComponent(datasLbl1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(card1Layout.createSequentialGroup()
                                            .addComponent(ucNameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                            .addGap(166, 166, 166)))
                                    .addComponent(textoDescritivoLbl1)
                                    .addGap(12, 12, 12))
                                .addGroup(card1Layout.createSequentialGroup()
                                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(card1Layout.createSequentialGroup()
                                            .addComponent(dataFimExpoLbl1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(anoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(diaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(card1Layout.createSequentialGroup()
                                            .addComponent(tituloLbl1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tituloTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(card1Layout.createSequentialGroup()
                                            .addComponent(inicioExpoLbl1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(anoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, card1Layout.createSequentialGroup()
                            .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, card1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(localLbl1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(localTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, card1Layout.createSequentialGroup()
                                    .addComponent(dataAberturaSubmissaoLbl1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anoInicioCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesInicioCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diaInicioCand, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, card1Layout.createSequentialGroup()
                                    .addComponent(dataLimiteDetecaoConflitosLbl1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anoFimDetecaoConflitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesFimDetecaoConflitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diaFimDetecaoConflitos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, card1Layout.createSequentialGroup()
                                    .addComponent(dataEncerramentoSubmissaoCandLbl1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anoFimCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesFimCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diaFimCand, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizadoresLbl1)
                    .addComponent(selectOrgLbl1))
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(orgSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addOrganizadorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                                .addComponent(registExpoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeOrganizadorBtn1)
                        .addGap(11, 11, 11)))
                .addContainerGap())
            .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(card1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoDescritivoLbl1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(card1Layout.createSequentialGroup()
                            .addComponent(ucNameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tituloLbl1)
                                .addComponent(tituloTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(datasLbl1)
                            .addGap(29, 29, 29)
                            .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inicioExpoLbl1)
                                .addComponent(anoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dataFimExpoLbl1)
                                .addComponent(anoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(diaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataAberturaSubmissaoLbl1)
                        .addComponent(anoInicioCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mesInicioCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(diaInicioCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mesFimCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(anoFimCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataEncerramentoSubmissaoCandLbl1)
                        .addComponent(diaFimCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataLimiteDetecaoConflitosLbl1)
                        .addComponent(anoFimDetecaoConflitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mesFimDetecaoConflitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(diaFimDetecaoConflitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50)
                    .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(localLbl1)
                        .addComponent(localTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(110, 110, 110)))
        );

        getContentPane().add(card1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtn1ActionPerformed

    private void anoFimDetecaoConflitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoFimDetecaoConflitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoFimDetecaoConflitosActionPerformed

    private void tituloTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTxt1ActionPerformed

    private void registExpoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registExpoBtn1ActionPerformed
        registExpoBtn1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (model.getSize() >= 2) {
                    if (tituloTxt1.getText() != null && textoDescritivoTxt1.getText() != null && dataInicio != null && dataFim != null && dataInicioSubCand != null && dataFimSubCand != null && dataFimDetecaoConflitos != null) {
                        ctrl.registarOrganizadores();
                        inicializarDatas();
                        ctrl.setDados(tituloTxt1.getText(), textoDescritivoTxt1.getText(), dataInicio, dataFim, dataInicioSubCand, dataFimSubCand, dataFimDetecaoConflitos, new Local(localTxt1.getText()));
                        ctrl.registaExposicao();
                    } else {
                        JOptionPane.showMessageDialog(null, "Todos os campos são de preenchimento obrigatório", "Dados Insuficientes", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Tem de escolher pelo menos 2 organizadores", "Organizadores Insuficientes", JOptionPane.ERROR_MESSAGE);
                }
            }

            private void inicializarDatas() {
                int ano1 = (Integer) anoInicio.getSelectedItem();
                int ano2 = (Integer) anoFim.getSelectedItem();
                int ano3 = (Integer) anoInicioCand.getSelectedItem();
                int ano4 = (Integer) anoFimCand.getSelectedItem();
                int ano5 = (Integer) anoFimDetecaoConflitos.getSelectedItem();
                int mes1 = (Integer) mesInicio.getSelectedIndex() + 1;
                int mes2 = (Integer) mesFim.getSelectedIndex() + 1;
                int mes3 = (Integer) mesInicioCand.getSelectedIndex() + 1;
                int mes4 = (Integer) mesFimCand.getSelectedIndex() + 1;
                int mes5 = (Integer) mesFimDetecaoConflitos.getSelectedIndex() + 1;
                int dia1 = (Integer) diaInicio.getSelectedItem();
                int dia2 = (Integer) diaFim.getSelectedItem();
                int dia3 = (Integer) diaInicioCand.getSelectedItem();
                int dia4 = (Integer) diaFimCand.getSelectedItem();
                int dia5 = (Integer) diaFimDetecaoConflitos.getSelectedItem();
                dataInicio = new Data(ano1, mes1, dia1);
                dataFim = new Data(ano2, mes2, dia2);
                dataInicioSubCand = new Data(ano3, mes3, dia3);
                dataFimSubCand = new Data(ano4, mes4, dia4);
                dataFimDetecaoConflitos = new Data(ano5, mes5, dia5);
            }
        });
    }//GEN-LAST:event_registExpoBtn1ActionPerformed

    private void anoFimCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoFimCandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoFimCandActionPerformed

    private void mesFimDetecaoConflitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesFimDetecaoConflitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesFimDetecaoConflitosActionPerformed

    private void anoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoInicioActionPerformed

    private void addOrganizadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizadorBtnActionPerformed
        addOrganizadorBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                organizadorSelecionado = (Organizador) orgSelectionComboBox.getSelectedItem();
                model.add(organizadorSelecionado);
                ctrl.addOrganizador(organizadorSelecionado);
            }
        });
    }//GEN-LAST:event_addOrganizadorBtnActionPerformed

    private void anoInicioCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoInicioCandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoInicioCandActionPerformed

    private void mesFimCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesFimCandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesFimCandActionPerformed

    private void removeOrganizadorBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrganizadorBtn1ActionPerformed
        int index = organizadoresList1.getSelectedIndex();
        model.remove(index);
        ctrl.removerOrganizador(index);
    }//GEN-LAST:event_removeOrganizadorBtn1ActionPerformed

    private void localTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localTxt1ActionPerformed

    private void anoFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoFimActionPerformed

    private void mesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesInicioActionPerformed
        int mes = mesInicio.getSelectedIndex() + 1;
        switch (mes) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                diaInicio.setModel(new ModelComboBoxDias(31));
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                diaInicio.setModel(new ModelComboBoxDias(30));
                break;
            case 2:
                if (Data.isAnoBissexto((Integer) anoInicio.getSelectedItem())) {
                    diaInicio.setModel(new ModelComboBoxDias(29));
                } else {
                    diaInicio.setModel(new ModelComboBoxDias(28));
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_mesInicioActionPerformed

    private void diaFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaFimActionPerformed

    }//GEN-LAST:event_diaFimActionPerformed

    private void diaInicioCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaInicioCandActionPerformed

    }//GEN-LAST:event_diaInicioCandActionPerformed

    private void diaFimCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaFimCandActionPerformed
        int mes = mesFimCand.getSelectedIndex() + 1;
        if (mes == 1 || mes == 3 || mes == 5 || mes == 7 || mes == 8 || mes == 10 || mes == 12) {
            diaFimCand.setModel(new ModelComboBoxDias(31));
        } else if (mes == 4 || mes == 6 || mes == 9 || mes == 11) {
            diaFimCand.setModel(new ModelComboBoxDias(30));
        } else if (mes == 2) {
            if (Data.isAnoBissexto((Integer) anoFimCand.getSelectedItem())) {
                diaFimCand.setModel(new ModelComboBoxDias(29));
            } else {
                diaFimCand.setModel(new ModelComboBoxDias(28));
            }
        }
    }//GEN-LAST:event_diaFimCandActionPerformed

    private void diaFimDetecaoConflitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaFimDetecaoConflitosActionPerformed
        int mes = mesFimDetecaoConflitos.getSelectedIndex() + 1;
        switch (mes) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                diaFimDetecaoConflitos.setModel(new ModelComboBoxDias(31));
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                diaFimDetecaoConflitos.setModel(new ModelComboBoxDias(30));
                break;
            case 2:
                if (Data.isAnoBissexto((Integer) anoFimDetecaoConflitos.getSelectedItem())) {
                    diaFimDetecaoConflitos.setModel(new ModelComboBoxDias(29));
                } else {
                    diaFimDetecaoConflitos.setModel(new ModelComboBoxDias(28));
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_diaFimDetecaoConflitosActionPerformed

    private void orgSelectionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgSelectionComboBoxActionPerformed
        modelSelectOrg.setSelectedItem(anoFim);
    }//GEN-LAST:event_orgSelectionComboBoxActionPerformed

    private void mesFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesFimActionPerformed
        int mes = mesFim.getSelectedIndex() + 1;
        switch (mes) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                diaFim.setModel(new ModelComboBoxDias(31));
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                diaFim.setModel(new ModelComboBoxDias(30));
                break;
            case 2:
                if (Data.isAnoBissexto((Integer) anoFim.getSelectedItem())) {
                    diaFim.setModel(new ModelComboBoxDias(29));
                } else {
                    diaFim.setModel(new ModelComboBoxDias(28));
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_mesFimActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrganizadorBtn;
    private javax.swing.JComboBox<String> anoFim;
    private javax.swing.JComboBox<String> anoFimCand;
    private javax.swing.JComboBox<String> anoFimDetecaoConflitos;
    private javax.swing.JComboBox<String> anoInicio;
    private javax.swing.JComboBox<String> anoInicioCand;
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JPanel card1;
    private javax.swing.JLabel dataAberturaSubmissaoLbl1;
    private javax.swing.JLabel dataEncerramentoSubmissaoCandLbl1;
    private javax.swing.JLabel dataFimExpoLbl1;
    private javax.swing.JLabel dataLimiteDetecaoConflitosLbl1;
    private javax.swing.JLabel datasLbl1;
    private javax.swing.JComboBox<String> diaFim;
    private javax.swing.JComboBox<String> diaFimCand;
    private javax.swing.JComboBox<String> diaFimDetecaoConflitos;
    private javax.swing.JComboBox<String> diaInicio;
    private javax.swing.JComboBox<String> diaInicioCand;
    private javax.swing.JLabel inicioExpoLbl1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel localLbl1;
    private javax.swing.JTextField localTxt1;
    private javax.swing.JComboBox<String> mesFim;
    private javax.swing.JComboBox<String> mesFimCand;
    private javax.swing.JComboBox<String> mesFimDetecaoConflitos;
    private javax.swing.JComboBox<String> mesInicio;
    private javax.swing.JComboBox<String> mesInicioCand;
    private javax.swing.JComboBox<String> orgSelectionComboBox;
    private javax.swing.JLabel organizadoresLbl1;
    private javax.swing.JList organizadoresList1;
    private javax.swing.JButton registExpoBtn1;
    private javax.swing.JButton removeOrganizadorBtn1;
    private javax.swing.JLabel selectOrgLbl1;
    private javax.swing.JLabel textoDescritivoLbl1;
    private javax.swing.JTextArea textoDescritivoTxt1;
    private javax.swing.JLabel tituloLbl1;
    private javax.swing.JTextField tituloTxt1;
    private javax.swing.JLabel ucNameLbl1;
    // End of variables declaration//GEN-END:variables
}
