package lapr.project.ui;

import java.util.List;
import javax.swing.*;
import lapr.project.controller.CriarStandsController;
import lapr.project.exceptions.AreaErradaException;
import lapr.project.model.*;

/**
 * UI do UC Criar stands
 *
 * @author G29
 */
public class JFrameCriarStandsUI extends javax.swing.JFrame {

    /**
     * Largura da janela
     */
    private static final int LARGURA_JANELA = 510;

    /**
     * Altura da janela
     */
    private static final int ALTURA_JANELA = 410;

    /**
     * Referência à JFrame do menu
     */
    private final JFrame jFrameMenuPrincipal;

    /**
     * Centro de exposições atual
     */
    private final CentroExposicoes centroExposicoesAtual;

    /**
     * Controller deste Caso de Uso - CriarStandsController
     */
    private final CriarStandsController controller;
    
    /**
     * Lista de stands existentes no centro de exposições atual
     */
    private final List<Stand> listaStands;

    /**
     * Creates new form JFrameCriarStandsUI
     *
     * @param jFrameMenuPrincipal JFrame do menu principal
     * @param centroExposicoes Centro de exposições atual
     */
    public JFrameCriarStandsUI(JFrame jFrameMenuPrincipal, CentroExposicoes centroExposicoes) {
        super("Criar stands");
        this.jFrameMenuPrincipal = jFrameMenuPrincipal;
        this.centroExposicoesAtual = centroExposicoes;
        this.controller = new CriarStandsController(this.centroExposicoesAtual);
        controller.getRegistoStands();
        this.listaStands = controller.getListaStands();

        initComponents();

        setLocationRelativeTo(null);
        setSize(LARGURA_JANELA, ALTURA_JANELA);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCard1Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDStand = new javax.swing.JTextField();
        jTextFieldAreaStand = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonCriarStand = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListStandsExistentes = new javax.swing.JList<>();
        jButtonTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabelCard1Titulo.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabelCard1Titulo.setText("Criar stands");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Introduza os dados do novo stand");

        jLabel2.setText("ID:");

        jLabel3.setText("Área:");

        jLabel8.setText("m²");

        jButtonCriarStand.setText("Criar stand");
        jButtonCriarStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarStandActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Stands existentes:");

        jListStandsExistentes.setModel(new ModeloListaStands(this.listaStands));
        jScrollPane1.setViewportView(jListStandsExistentes);

        jButtonTerminar.setText("Terminar");
        jButtonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAreaStand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldIDStand)))
                        .addGap(35, 35, 35)
                        .addComponent(jButtonCriarStand)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCard1Titulo)
                .addGap(185, 185, 185))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTerminar)
                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelCard1Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIDStand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAreaStand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jButtonCriarStand, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonTerminar)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarActionPerformed
        this.jFrameMenuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTerminarActionPerformed

    private void jButtonCriarStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarStandActionPerformed
        boolean standCriado;
        if (verificarCamposVazios() == false) {
            try {
                standCriado = controller.criarStand(jTextFieldIDStand.getText(), jTextFieldAreaStand.getText());
                if (standCriado == false) {
                    JOptionPane.showMessageDialog(rootPane, "O ID do stand introduzido já existe. Este parametro deve de ser único!",
                            "Informação inválida",
                            JOptionPane.WARNING_MESSAGE);
                } else {
                    jListStandsExistentes.setModel(new ModeloListaStands(this.listaStands));
                    JOptionPane.showMessageDialog(rootPane, "Stand criado.",
                            "Sucesso",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (AreaErradaException exception) {
                JOptionPane.showMessageDialog(rootPane, exception.getMessage(),
                        "Informação errada",
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não pode deixar nenhum campo em branco!",
                    "Informação em falta",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCriarStandActionPerformed

    private boolean verificarCamposVazios() {
        if (jTextFieldIDStand.getText().isEmpty() || jTextFieldAreaStand.getText().isEmpty()) {
            return true;
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarStand;
    private javax.swing.JButton jButtonTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCard1Titulo;
    private javax.swing.JList<String> jListStandsExistentes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAreaStand;
    private javax.swing.JTextField jTextFieldIDStand;
    // End of variables declaration//GEN-END:variables
}
