package lapr.project.ui;

import lapr.project.ui.model.AbstractListModelConflitosDeInteresseCandidaturaADemonstracao;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.*;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import lapr.project.controller.AtualizarConflitoDeInteresseCandidaturaADemonstracaoController;
import lapr.project.model.*;
import lapr.project.ui.model.*;

/**
 *
 * @author G29
 */
public class JFrameAtualizarConflitoDeInteresseCandidaturaADemonstracao extends javax.swing.JFrame {

    private transient AtualizarConflitoDeInteresseCandidaturaADemonstracaoController CTRL;

    private static final String DESCRICAO_EXPOSICAO_POR_OMISSAO = "A apresentar a descrição da esposição selecionada";
    private static final String LOCAL_EXPOSICAO_POR_OMISSAO = "A apresentar o nome do local de realização para a exposição selecionada";
    private static final String DATA_INICIO_E_FIM_POR_OMISSAO = "00/00/0000";

    /**
     * Lista de exposições
     */
    private transient List<Exposicao> listaExposicoes;

    /**
     * Lista de candidaturas
     */
    private transient List<CandidaturaADemonstracao> listaCandidaturas;

    /**
     *
     */
    private transient List<ConflitoDeInteresseDemonstracao> listaConflitos;

    /**
     *
     */
    private transient List<TipoConflitoDemonstracao> listaTiposConflito;

    private transient List<Demonstracao> listaDemonstracoes;

    /**
     * JFramedo menu principal. Usado no final deste UC para que o menu volte a
     * estar visível
     */
    private JFrame mainMenu;

    /**
     * Creates new form
     * JFrameAtualizarConflitoDeInteresseCandidaturaADemonstracao
     *
     * @param mainMenu - Menu principal de onde esta insterface é chamada
     * @param username - username do FAE que iniciou a UC
     * @param ce - centro de Exposições
     */
    public JFrameAtualizarConflitoDeInteresseCandidaturaADemonstracao(JFrame mainMenu, String username, CentroExposicoes ce) {
        this.mainMenu = mainMenu;
        CTRL = new AtualizarConflitoDeInteresseCandidaturaADemonstracaoController(username, ce);
        listaExposicoes = CTRL.getFaeExpos();
        if (listaExposicoes.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não existem Exposições para as quais é FAE de uma demonstração.");
            mainMenu.setVisible(true);
        } else {
            initComponents();
        }
    }

    private void passaParaPanel1() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card1");
        setSize(this.getSize());

    }

    private void passaParaPanel2() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card2");
        setSize(this.getSize());
    }

    private void passaParaPanel3() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card3");
        setSize(this.getSize());
    }

    private void passaParaPanel4() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card4");
        setSize(this.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricaoDemonstracao = new javax.swing.JTextArea();
        jComboBoxEscolherDemonstracao = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxSelectCandidatura = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        botaoCriarConflito = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboBoxSelectTipoConflito = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabelCard1Titulo1 = new javax.swing.JLabel();
        botaoSelecionaExpo1 = new javax.swing.JButton();
        botaoCancelar1 = new javax.swing.JButton();
        jPanelCard1DescricaoExposicao1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaCard1DescricaoExposicao1 = new javax.swing.JTextArea();
        jPanelCard1Duracao1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelCard1DataInicio1 = new javax.swing.JLabel();
        jLabelCard1DataFim1 = new javax.swing.JLabel();
        jPanelCard1Local1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaCard1LocalExposicao1 = new javax.swing.JTextArea();
        comboBoxCard1EscolherExposicao1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Selecione uma demonstração");

        jButton9.setText("Voltar atrás");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Continuar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextAreaDescricaoDemonstracao.setColumns(20);
        jTextAreaDescricaoDemonstracao.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescricaoDemonstracao);

        jComboBoxEscolherDemonstracao.setModel(new ComboBoxModelDemonstracoes(listaDemonstracoes));
        jComboBoxEscolherDemonstracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEscolherDemonstracaoActionPerformed(evt);
            }
        });

        jLabel14.setText("Descrição:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton9)
                        .addGap(201, 201, 201)
                        .addComponent(jButton10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jComboBoxEscolherDemonstracao, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxEscolherDemonstracao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, "card2");
        jPanel2.getAccessibleContext().setAccessibleName("card2");

        jList1.setModel(new AbstractListModelConflitosDeInteresseCandidaturaADemonstracao(listaConflitos));
        jScrollPane1.setViewportView(jList1);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar Conflito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Adicionar Conflito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("  Atualizar Conflitos de Interesse  ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Conflitos Existentes:");

        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(9, 9, 9)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, "card3");
        jPanel3.getAccessibleContext().setAccessibleName("card3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("  Adicionar Conflito de Interesse  ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboBoxSelectCandidatura.setModel(new ComboBoxModelCandidaturaADemonstracao(listaCandidaturas));
        comboBoxSelectCandidatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSelectCandidaturaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Selecione uma candidatura em conflito.");

        botaoCriarConflito.setText("Criar Conflito");
        botaoCriarConflito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarConflitoActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Selecione um tipo de conflito.");

        comboBoxSelectTipoConflito.setModel(new ComboBoxModelTipoDeConflitoDemonstracao(listaTiposConflito));
        comboBoxSelectTipoConflito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSelectTipoConflitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboBoxSelectCandidatura, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxSelectTipoConflito, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCriarConflito))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSelectCandidatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSelectTipoConflito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(botaoCriarConflito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoVoltar)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel4, "card4");
        jPanel4.getAccessibleContext().setAccessibleName("card4");

        jLabelCard1Titulo1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabelCard1Titulo1.setText("Escolha a exposição pretendida");
        jLabelCard1Titulo1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        botaoSelecionaExpo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoSelecionaExpo1.setText("Selecionar exposição");
        botaoSelecionaExpo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionaExpo1ActionPerformed(evt);
            }
        });

        botaoCancelar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCancelar1.setText("Cancelar");
        botaoCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelar1ActionPerformed(evt);
            }
        });

        jPanelCard1DescricaoExposicao1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descricao", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanelCard1DescricaoExposicao1.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setBorder(null);
        jScrollPane4.setRequestFocusEnabled(false);

        textAreaCard1DescricaoExposicao1.setEditable(false);
        textAreaCard1DescricaoExposicao1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        textAreaCard1DescricaoExposicao1.setColumns(20);
        textAreaCard1DescricaoExposicao1.setLineWrap(true);
        textAreaCard1DescricaoExposicao1.setRows(5);
        textAreaCard1DescricaoExposicao1.setText("A apresentar a descrição da demonstração selecionada");
        textAreaCard1DescricaoExposicao1.setToolTipText("");
        textAreaCard1DescricaoExposicao1.setWrapStyleWord(true);
        textAreaCard1DescricaoExposicao1.setBorder(null);
        jScrollPane4.setViewportView(textAreaCard1DescricaoExposicao1);

        jPanelCard1DescricaoExposicao1.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanelCard1Duracao1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Duração", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("De");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("até");

        jLabelCard1DataInicio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCard1DataInicio1.setText("00/00/0000");

        jLabelCard1DataFim1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCard1DataFim1.setText("00/00/0000");

        javax.swing.GroupLayout jPanelCard1Duracao1Layout = new javax.swing.GroupLayout(jPanelCard1Duracao1);
        jPanelCard1Duracao1.setLayout(jPanelCard1Duracao1Layout);
        jPanelCard1Duracao1Layout.setHorizontalGroup(
            jPanelCard1Duracao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCard1Duracao1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCard1DataInicio1)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabelCard1DataFim1)
                .addGap(32, 32, 32))
        );
        jPanelCard1Duracao1Layout.setVerticalGroup(
            jPanelCard1Duracao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCard1Duracao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelCard1DataInicio1)
                .addComponent(jLabelCard1DataFim1))
        );

        jPanelCard1Local1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Local", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jScrollPane5.setBorder(null);

        jTextAreaCard1LocalExposicao1.setEditable(false);
        jTextAreaCard1LocalExposicao1.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        jTextAreaCard1LocalExposicao1.setColumns(20);
        jTextAreaCard1LocalExposicao1.setLineWrap(true);
        jTextAreaCard1LocalExposicao1.setRows(5);
        jTextAreaCard1LocalExposicao1.setText("A apresentar o local da exposição selecionada");
        jTextAreaCard1LocalExposicao1.setWrapStyleWord(true);
        jTextAreaCard1LocalExposicao1.setBorder(null);
        jScrollPane5.setViewportView(jTextAreaCard1LocalExposicao1);

        javax.swing.GroupLayout jPanelCard1Local1Layout = new javax.swing.GroupLayout(jPanelCard1Local1);
        jPanelCard1Local1.setLayout(jPanelCard1Local1Layout);
        jPanelCard1Local1Layout.setHorizontalGroup(
            jPanelCard1Local1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelCard1Local1Layout.setVerticalGroup(
            jPanelCard1Local1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        comboBoxCard1EscolherExposicao1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboBoxCard1EscolherExposicao1.setModel(new ComboBoxModelExposicoes(this.listaExposicoes));
        comboBoxCard1EscolherExposicao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCard1EscolherExposicao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(comboBoxCard1EscolherExposicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabelCard1Titulo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelCard1DescricaoExposicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCard1Duracao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(botaoSelecionaExpo1))
                            .addComponent(jPanelCard1Local1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCard1Titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxCard1EscolherExposicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelCard1Duracao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCard1Local1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoCancelar1)
                            .addComponent(botaoSelecionaExpo1))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addComponent(jPanelCard1DescricaoExposicao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card1");
        jPanel1.getAccessibleContext().setAccessibleName("card1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSelecionaExpo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionaExpo1ActionPerformed
        Exposicao e = (Exposicao) comboBoxCard1EscolherExposicao1.getSelectedItem();
        if (e != null) {
            CTRL.selectExpo(e);
            listaDemonstracoes = CTRL.getListaDemonstracoes();
            passaParaPanel2();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tem de selecionar uma exposição primeiro!", "Exposição em falta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoSelecionaExpo1ActionPerformed

    private void botaoCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelar1ActionPerformed
        dispose();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_botaoCancelar1ActionPerformed

    private void comboBoxCard1EscolherExposicao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCard1EscolherExposicao1ActionPerformed
        if (comboBoxCard1EscolherExposicao1.getSelectedItem() != null) {
            Exposicao e = (Exposicao) comboBoxCard1EscolherExposicao1.getSelectedItem();
            textAreaCard1DescricaoExposicao1.setText(e.getDescricao());
            jTextAreaCard1LocalExposicao1.setText(e.getLocal().getMorada());
            jLabelCard1DataInicio1.setText(e.getDataInicio().toAnoMesDiaString());
            jLabelCard1DataFim1.setText(e.getDataFim().toString());
            CTRL.selectExpo(e);
        } else {
            textAreaCard1DescricaoExposicao1.setText(DESCRICAO_EXPOSICAO_POR_OMISSAO);
            jTextAreaCard1LocalExposicao1.setText(LOCAL_EXPOSICAO_POR_OMISSAO);
            jLabelCard1DataInicio1.setText(DATA_INICIO_E_FIM_POR_OMISSAO);
            jLabelCard1DataFim1.setText(DATA_INICIO_E_FIM_POR_OMISSAO);
        }
    }//GEN-LAST:event_comboBoxCard1EscolherExposicao1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        passaParaPanel2();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jList1.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione primeiro um conflito.", "Sem seleção", ERROR_MESSAGE);
        } else {
            int[] paraEliminar = jList1.getSelectedIndices();
            for (int x : paraEliminar) {
                CTRL.removeConflito(listaConflitos.get(x));
            }
            listaConflitos = CTRL.getListaConflitos();
            jList1.setModel(new AbstractListModelConflitosDeInteresseCandidaturaADemonstracao(listaConflitos));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CTRL.pullRegistoDeTiposDeConflito();
        listaCandidaturas = CTRL.getListaCandidaturas();
        listaTiposConflito = CTRL.getListaDeTiposConflito();
        passaParaPanel4();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboBoxSelectCandidaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSelectCandidaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSelectCandidaturaActionPerformed

    private void botaoCriarConflitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarConflitoActionPerformed
        CandidaturaADemonstracao cand = listaCandidaturas.get(comboBoxSelectCandidatura.getSelectedIndex());
        TipoConflitoDemonstracao tipo = listaTiposConflito.get(comboBoxSelectTipoConflito.getSelectedIndex());
        if (cand == null) {
            JOptionPane.showMessageDialog(null, "Tem que selecionar uma candidatura", "Erro", JOptionPane.WARNING_MESSAGE);
        } else if (tipo == null) {
            JOptionPane.showMessageDialog(null, "Tem que selecionar um tipo de conflito", "Erro", JOptionPane.WARNING_MESSAGE);
        } else {
            CTRL.setCandidatura(cand);
            CTRL.setTipoConflito(tipo);
            if (CTRL.validaConflito()) {
                CTRL.registaConflito();
                listaConflitos = CTRL.getListaConflitos();
                jList1.setModel(new AbstractListModelConflitosDeInteresseCandidaturaADemonstracao(listaConflitos));
                passaParaPanel3();
            } else {
                JOptionPane.showMessageDialog(null, "Esse conflito já existe!", "Conflito Repetido.", ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botaoCriarConflitoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        passaParaPanel3();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void comboBoxSelectTipoConflitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSelectTipoConflitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSelectTipoConflitoActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        passaParaPanel1();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        CTRL.selectDemo(listaDemonstracoes.get(jComboBoxEscolherDemonstracao.getSelectedIndex()));
        listaConflitos = CTRL.getListaConflitos();
        passaParaPanel3();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBoxEscolherDemonstracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEscolherDemonstracaoActionPerformed
        if (jComboBoxEscolherDemonstracao.getSelectedItem() != null) {
            jTextAreaDescricaoDemonstracao.setText(listaDemonstracoes.get(jComboBoxEscolherDemonstracao.getSelectedIndex()).getDescricao());
        } else {
            jTextAreaDescricaoDemonstracao.setText("Descrição da demonstração selecionada.... Por favor selecione uma demonstração.");
        }
    }//GEN-LAST:event_jComboBoxEscolherDemonstracaoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar1;
    private javax.swing.JButton botaoCriarConflito;
    private javax.swing.JButton botaoSelecionaExpo1;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboBoxCard1EscolherExposicao1;
    private javax.swing.JComboBox<String> comboBoxSelectCandidatura;
    private javax.swing.JComboBox<String> comboBoxSelectTipoConflito;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBoxEscolherDemonstracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCard1DataFim1;
    private javax.swing.JLabel jLabelCard1DataInicio1;
    private javax.swing.JLabel jLabelCard1Titulo1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCard1DescricaoExposicao1;
    private javax.swing.JPanel jPanelCard1Duracao1;
    private javax.swing.JPanel jPanelCard1Local1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaCard1LocalExposicao1;
    private javax.swing.JTextArea jTextAreaDescricaoDemonstracao;
    private javax.swing.JTextArea textAreaCard1DescricaoExposicao1;
    // End of variables declaration//GEN-END:variables
}
